apiVersion: v1
kind: Service
metadata:
    name: "qubes-4504"
    labels:
        app: "qubes-4504"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "qubes-4504"